name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Copy Files to VM
        run: |
          scp -i ${{ secrets.SSH_PRIVATE_KEY }} -r ./* ${{ secrets.VM_USERNAME }}@${{ secrets.VM_HOST }}:$GITHUB_WORKSPACE/

      - name: SSH into VM and Run Commands
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.VM_USERNAME }}@${{ secrets.VM_HOST }} "cd $GITHUB_WORKSPACE && \
            git pull origin main && \
            npm install && \
            npm install -g pm2 && \
            pm2 restart app.js"

      - name: Notify Deployment Status
        if: success()
        run: echo "Deployment successful!"

      - name: Notify Deployment Failure
        if: failure()
        run: echo "Deployment failed!" && exit 1
