name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Copy Files to VM
        uses: appleboy/scp-action@0.1.1
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: .
          target: test/

      - name: SSH into VM and Deploy
        uses: appleboy/ssh-action@0.1.5
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd test/
            npm install
            sudo pm2 start app.js

      - name: Notify Deployment Status
        if: success()
        run: echo "Deployment successful!"

      - name: Notify Deployment Failure
        if: failure()
        run: echo "Deployment failed!" && exit 1
