name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set Up Node.js and PM2
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm
          sudo npm install -g pm2
          export PATH=$PATH:/usr/bin/npm:/usr/bin

      - name: Display Node.js and NPM Versions
        run: |
          node --version
          npm --version

      - name: Install Dependencies
        run: npm install

      - name: Display Directory Contents
        run: ls -la

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd $GITHUB_WORKSPACE
            git pull origin main
            npm install
            pm2 restart app.js

      - name: Notify Deployment Status
        if: success()
        run: echo "Deployment successful!"

      - name: Notify Deployment Failure
        if: failure()
        run: echo "Deployment failed!" && exit 1
